server:
  port: 8082

spring:
  main:
    banner-mode: "console"

prosess:
    cron: "5 * * * * *"
  integrasjon:
    joark:
      uri: http://localhost:8090
    sts:
      uri: http://localhost:8090
    api:
      uri: http://localhost:8090/tiltaksgjennomforing-api


