server:
  port: 8082

spring:
  main:
    banner-mode: "console"

prosess:
  jobb:
    cron: "15 * * * * *"
  integrasjon:
    joark:
      uri: http://localhost:8090
    sts:
      uri: http://localhost:8090
    api:
      uri: http://localhost:8091


