server.servlet.context-path: /tiltaksgjennomforing-prosess

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

logging:
  level:
    no.nav.tag.tiltaksgjennomforingprosess: INFO
    org.springframework.*: WARN
    org.flywaydb.*: WARN

spring:
  application:
    name: tiltaksgjennomforing-prosess
  main:
    banner-mode: "off"

prosess:
  cron:
  integrasjon:
    joark:
      uri: url
    sts:
      uri: url
      bruker: ${srvbruker}
      passord: ${srvpassord}
    tiltaksgjennomforing:
      uri: url
    dokgen:
      uri: http://tiltak-dokgen/template/tiltak-avtale/create-pdf
    pilot:
      pilotvirksomheter: ${tiltaksgjennomforing.pilot.pilotvirksomheter}

elector.path: ${ELECTOR_PATH}