prosess:
  cron: "0/5 * * * * *"
  integrasjon:
    joark:
      uri: https://dokarkiv.nais.adeo.no
    sts:
      uri: http://security-token-service.default.svc.nais.local
      bruker: ${tiltaksgjennomforing.consumer.user}
      passord: ${tiltaksgjennomforing.consumer.password}
    api:
      uri: https://arbeidsgiver.nais.adeo.no/tiltaksgjennomforing-api






