server.servlet.context-path: /tiltaksgjennomforing-prosess

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

logging:
  level:
    no.nav.tag.tiltaksgjennomforingprosess: INFO
    org.springframework.*: WARN
    org.flywaydb.*: WARN

spring:
  application:
    name: tiltaksgjennomforing-prosess
  main:
    banner-mode: "off"
  cache:
    type: caffeine

no.nav.security.jwt:
  client:
    registration:
      aad-graph:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      aad:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      aad-anonym:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

prosess:
  cron:
  integrasjon:
    joark:
      uri: url
    sts:
      uri: url
      bruker: ${srvbruker}
      passord: ${srvpassord}
    tiltaksgjennomforing:
      uri: url
    dokgen:
      uri: http://tiltak-dokgen/template/tiltak-avtale/create-pdf
    pilot:
      pilotvirksomheter: ${tiltaksgjennomforing.pilot.pilotvirksomheter}
      pilotenheter: ${tiltaksgjennomforing.pilot.pilotenheter}

caches:
  caffeine:
    - name: pdl_cache
      expiryInMinutes: 60
      maximumSize: 1000

elector.path: ${ELECTOR_PATH}
