logging:
  level:
    no.nav.tag.tiltaksgjennomforingprosess: ${process.log.level}

no.nav.security.jwt:
  client:
    registration:
      pdl-api:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-fss.pdl.pdl-api/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
prosess:
  cron: "0 0/5 7-19 ? * MON-FRI"
  integrasjon:
    joark:
      uri: https://dokarkiv.nais.adeo.no
    sts:
      uri: http://security-token-service.default.svc.nais.local
      bruker: ${tiltaksgjennomforing.consumer.user}
      passord: ${tiltaksgjennomforing.consumer.password}
    api:
      uri: http://tiltaksgjennomforing-api.arbeidsgiver.svc.nais.local/tiltaksgjennomforing-api
    persondata:
      uri: https://pdl-api.intern.nav.no/graphql







