logging:
  level:
    no.nav.tag.tiltaksgjennomforingprosess: ${process.log.level}

prosess:
  cron: "0 0/5 7-19 ? * MON-FRI"
  integrasjon:
    joark:
      uri: https://dokarkiv.nais.adeo.no
    sts:
      uri: http://security-token-service.default.svc.nais.local
      bruker: ${tiltaksgjennomforing.consumer.user}
      passord: ${tiltaksgjennomforing.consumer.password}
    api:
      uri: http://tiltaksgjennomforing-api.arbeidsgiver/tiltaksgjennomforing-api







