server:
  port: 8081
  ssl:
    key-store: file:${KEYSTORE_FIL}
    key-store-password: ${KEYSTORE_PWD}
    trust-store: file:${TRUSTSTORE_FIL}
    trust-store-password: ${TRUSTSTORE_PWD}

spring:
  main:
    banner-mode: "console"

prosess:
  jobb:
    cron: 5,10,20,30,40,50 * * ? * *
  integrasjon:
    joark:
      uri: https://dokarkiv-q1.nais.preprod.local
    sts:
      uri: https://security-token-service.nais.preprod.local
      bruker: ${tiltaksgjennomforing.consumer.user}
      passord: ${tiltaksgjennomforing.consumer.password}
    api:
      uri: https://arbeidsgiver.nais.preprod.local/tiltaksgjennomforing-api