prosess:
  cron: "0 10 * * * *"
  integrasjon:
    joark:
      uri: https://dokarkiv.nais.adeo.no
    sts:
      uri: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
      bruker: ${tiltaksgjennomforing.consumer.user}
      passord: ${tiltaksgjennomforing.consumer.password}
    api:
      uri: https://arbeidsgiver.nais.adeo.no/tiltaksgjennomforing-api






