spring:
  datasource:
    platform: postgres
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
    enabled: true

  main:
    banner-mode: "console"

journalpost:
  jobb:
    cron: 5,10,20,30,40,50 * * ? * *
  integrasjon:
    uri: http://localhost:8090

sts:
  uri: http://localhost:8090
  bruker: ${SRVBRUKER}
  passord: ${SRVPASSORD}