logging:
  level:
    no.nav.tag.tiltaksgjennomforingprosess: ${process.log.level}

prosess:
  cron: "5/30 * 07-19 * * MON-FRI"
  integrasjon:
    joark:
      uri: https://dokarkiv.nais.adeo.no
    sts:
      uri: http://security-token-service
      bruker: ${tiltaksgjennomforing.consumer.user}
      passord: ${tiltaksgjennomforing.consumer.password}
    api:
      uri: http://tiltaksgjennomforing-api.arbeidsgiver/tiltaksgjennomforing-api
    unleash:
      uri: https://unleash.nais.adeo.no/api/
    dokgen:
      uri: http://tag-dokgen/template/tiltak-avtale/create-pdf





