spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
    enabled: true


  kafka:
    consumer:
      group-id: tag-tiltak
      auto-offset-reset: earliest
      bootstrap-servers: ${spring.embedded.kafka.brokers}
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties-spring-json-value-default-type: no.nav.tag.tiltaksgjennomforingprosess.domene.Avtale
    template:
      default-topic: "godkjentArbeidsAvtale"

    banner-mode: "console"

journalpost:
  integrasjon:
    joark:
      uri: http://localhost:8090
    sts:
      uri: http://localhost:8090
