spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
  h2:
    console:
      enabled: true

tiltaksgjennomforing:
  database:
    database-navn: tiltaksgjennomforing-preprod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss
    minimum-idle: 1
    maximum-pool-size: 5
    max-lifetime: 300000

journalpost:
  jobb:
    cron: 5,10,20,30,40,50 * * ? * *
  integrasjon:
    uri: https://dokarkiv-q1.nais.preprod.local

sts:
  uri: https://security-token-service.nais.preprod.local