logging:
  level:
    no.nav.tag.tiltaksgjennomforingprosess: ${process.log.level}

prosess:
  cron: "5/30 * 07-20 * * MON-FRI"
  integrasjon:
    joark:
      uri: https://dokarkiv-q1.nais.preprod.local
    sts:
      uri: http://security-token-service.default.svc.nais.local
      bruker: ${tiltaksgjennomforing.consumer.user}
      passord: ${tiltaksgjennomforing.consumer.password}
    api:
      uri: http://tiltaksgjennomforing-api.arbeidsgiver/tiltaksgjennomforing-api
    unleash:
      uri: https://unleash.nais.io/api/
    dokgen:
      uri: https://tag-dokgen.nais.preprod.local/template/tiltak-avtale/create-pdf

