server.servlet.context-path: /tiltaksgjennomforing-prosess

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  application:
    name: tiltaksgjennomforing-prosess
  main:
    banner-mode: "off"

prosess:
  jobb:
    cron:
  integrasjon:
    joark:
      uri: url
    sts:
      uri: url
      bruker: ${srvbruker}
      passord: ${srvpassord}
    tiltaksgjennomforing:
      uri: url