server.servlet.context-path: /tiltaksgjennomforing-prosess

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring:
  application:
    name: tiltaksgjennomforing-prosess
  main:
    banner-mode: "off"
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: false

  kafka:
    bootstrap-servers:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


journalpost:
  jobb-cron: 5,10,20,30,40,50 * * ? * *
  integrasjon:
    joark:
      uri: http://localhost:8090
    sts:
      uri: http://localhost:8090
      bruker: ${srvbruker}
      passord: ${srvpassord}

tiltaksgjennomforing:
  integrasjon:
    uri: http://localhost:8080

