spring:
  main:
    banner-mode: "console"

prosess:
  jobb:
    cron: 15/15 0 0 ? * *
  integrasjon:
    joark:
      uri: http://localhost:8090
    sts:
      uri: http://localhost:8090
    api:
      uri: http://localhost:8080/tiltaksgjennomforing-api


