server:
  port: 8082

spring:
  main:
    banner-mode: "console"

prosess:
  cron: "2/10 * * * * *"
  integrasjon:
    joark:
      uri: http://localhost:8091/
    sts:
      uri: http://localhost:8091/
    api:
      uri: http://localhost:8090/tiltaksgjennomforing-api
 #     uri: http://localhost:8091/


