apiVersion: nais.io/v1
kind: Alert
metadata:
  name: tiltaksgjennomforing-prosess-alert
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: '#arbeidsgiver-notifications-test'
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: up{app="tiltaksgjennomforing-prosess", job="kubernetes-pods"} == 0
      for: 30m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod tiltaksgjennomforing-prosess -n arbeidsgiver` for events, og `kubectl logs tiltaksgjennomforing-prosess -n arbeidsgiver` for logger"
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="tiltaksgjennomforing-prosess",log_level=~"Warning|Error"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="tiltaksgjennomforing-prosess"}[5m]))) > 10
      for: 10m
      description: "{{ $labels.app }} feiler mye {{ $labels.kubernetes_namespace }}"
      action: "Sjekk loggene til app {{ $labels.app }} i namespace {{ $labels.kubernetes_namespace }}, for å se hvorfor det er så mye feil"
    - alert: høy feilrate i logger test
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="tiltaksgjennomforing-prosess",log_level="Info"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="tiltaksgjennomforing-prosess"}[5m]))) > 10
      for: 10m
      description: "{{ $labels.app }} feiler mye {{ $labels.kubernetes_namespace }}"
      action: "Sjekk loggene til app {{ $labels.app }} i namespace {{ $labels.kubernetes_namespace }}, for å se hvorfor det er så mye feil"
    - alert: Warnings i prosess
      expr: round(sum(increase(logd_messages_total{log_app="tiltaksgjennomforing-prosess",log_level="Info"}[10m]))) > 2
      for: 10m
      description: "Nå smeller det i {{ $labels.app }} feilmeldinger i {{ $labels.kubernetes_namespace }}"
      action: "Sjekk loggene til app tiltaksgjennomforing-prosess: https://logs.adeo.no/goto/e8fbddda1b6f991a1d33970355649d0f"