apiVersion: nais.io/v1
kind: Alert
metadata:
  name: tiltaksgjennomforing-prosess-alert
  namespace: arbeidsgiver
  labels:
    app: tiltaksgjennomforing-prosess
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'arbeidsgiver-notifications'
      prependText: '<!here> | '
  alerts:
    - alert: applikasjon nede
      expr: up{app="tiltaksgjennomforing-prosess", job="kubernetes-pods"} == 0
      for: 5m
      description: "tiltaksgjennomforing-prosess er nede i arbeidsgiver"
      action: "`kubectl describe pod tiltaksgjennomforing-prosess -n arbeidsgiver` for events, og `kubectl logs tiltaksgjennomforing-prosess -n arbeidsgiver` for logger"
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="tiltaksgjennomforing-prosess",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="tiltaksgjennomforing-prosess"}[3m]))) > 10
      for: 10m
      action: "Sjekk loggene til app tiltaksgjennomforing-prosess i namespace arbeidsgiver, for å se hvorfor det er så mye feil"
