apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tiltaksgjennomforing-prosess
  namespace: arbeidsgiver
  labels:
    team: team-tiltak
spec:
  groups:
    - name: tiltaksgjennomforing-prosess-alerts
      rules:
        - alert: applikasjon nede
          expr: sum(up{app="tiltaksgjennomforing-prosess", job="nais-system/monitoring-apps-tenant"}) == 0
          for: 1s
          annotations:
            summary: tiltaksgjennomforing-prosess er nede
            action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
          labels:
            namespace: team-tiltak
            severity: critical

        - alert: Antall restarts
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"tiltaksgjennomforing-prosess"}[30m])) by (container) > 2
          for: 5m
          annotations:
            summary: tiltaksgjennomforing-prosess har restartet flere ganger siste halvtimen!
            action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
          labels:
            namespace: team-tiltak
            severity: critical

        - alert: tiltaksgjennomforing-prosess ERROR!
          expr: sum(increase(logd_messages_total{log_app="tiltaksgjennomforing-prosess",log_level="Error"}[10m])) > 0
          for: 10s
          annotations:
            summary: |-
              tiltaksgjennomforing-prosess har logget en feil :error: Sjekk loggene om noe bør gjøres!
            action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/goto/e8fbddda1b6f991a1d33970355649d0f"
          labels:
            namespace: team-tiltak
            severity: critical