apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-prosess
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  leaderElection: true
  liveness:
    path: /tiltaksgjennomforing-prosess/internal/healthcheck
    initialDelay: 30
  readiness:
    path: /tiltaksgjennomforing-prosess/internal/healthcheck
    initialDelay: 30
  ingresses:
    - {{ingress}}
  accessPolicy:
    outbound:
      rules:
        - application: pdl-api
          namespace: pdl
  vault:
    enabled: true
    paths:
      - kvPath: {{vault-default-path}}
        mountPath: "/var/run/secrets/nais.io/vault/"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring-profil}}
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-prosess/internal/actuator/prometheus


